kubectl apply -f deployment/kafka-configmap.yaml
kubectl apply -f deployment/db-configmap.yaml
kubectl apply -f deployment/db-secret.yam
kubectl apply -f deployment/postgres.yaml
kubectl apply -f deployment/zookeeper.yaml
kubectl apply -f deployment/kafka.yaml
kubectl apply -f deployment/udaconnect-person.yaml
kubectl apply -f deployment/udaconnect-connection.yaml
kubectl apply -f deployment/udaconnect-location.yaml
kubectl apply -f deployment/udaconnect-location-consumer.yaml
kubectl apply -f deployment/udaconnect-frontend.yaml