version: "3"
services:
  frontend:
    build:
      context: ./modules/frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - db
      - api  # Đảm bảo frontend khởi động sau khi API đã sẵn sàng

  api:
    build:
      context: ./modules/api
      dockerfile: Dockerfile
    container_name: api
    environment:
      DB_USERNAME: ct_admin
      DB_PASSWORD: Abc12345
      DB_NAME: geoconnections
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "5000:5000"
    depends_on:
      - db  # Đảm bảo API khởi động sau khi database đã sẵn sàng
  db:
    image: postgis/postgis:12-2.5-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: "ct_admin"
      POSTGRES_PASSWORD: "Abc12345"
      POSTGRES_DB: "geoconnections"
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data  # Map thư mục ./db-data trong thư mục hiện tại