version: "3"
services:
  frontend:
    build:
      context: ./modules/frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - db
      - api  # Đảm bảo frontend khởi động sau khi API đã sẵn sàng

  api:
    build:
      context: ./modules/api
      dockerfile: Dockerfile
    container_name: api
    environment:
      DB_USERNAME: ct_admin
      DB_PASSWORD: Abc12345
      DB_NAME: geoconnections
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "5000:5000"
    depends_on:
      - db
      - person
  person:
    build:
      context: ./modules/person
      dockerfile: Dockerfile
    container_name: person
    environment:
      DB_USERNAME: ct_admin
      DB_PASSWORD: Abc12345
      DB_NAME: geoconnections
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "5001:5000"
    depends_on:
      - db

  location:
    build:
      context: ./modules/location
      dockerfile: Dockerfile
    container_name: location
    environment:
      DB_USERNAME: ct_admin
      DB_PASSWORD: Abc12345
      DB_NAME: geoconnections
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "5005:5005"
    depends_on:
      - kafka

  location-consumer:
   build:
     context: ./modules/location-consumer
     dockerfile: Dockerfile
   container_name: location-consumer
   environment:
     DB_USERNAME: ct_admin
     DB_PASSWORD: Abc12345
     DB_NAME: geoconnections
     DB_HOST: db
     DB_PORT: 5432    
   depends_on:
     - kafka
  db:
    image: postgis/postgis:12-2.5-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: "ct_admin"
      POSTGRES_PASSWORD: "Abc12345"
      POSTGRES_DB: "geoconnections"
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data  # Map thư mục ./db-data trong thư mục hiện tại

  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:6.0.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_RETENTION_HOURS: 168