apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-connection
  name: udaconnect-connection
spec:
  ports:
  - name: "connection-svc-port"
    port: 5000
    targetPort: 5000
    nodePort: 30002
  selector:
    service: udaconnect-connection
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-connection
  name: udaconnect-connection
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-connection
  template:
    metadata:
      labels:
        service: udaconnect-connection
    spec:
      containers:
      - image: vuongdq2503/udaconnect-connection:latest
        name: udaconnect-connection
        imagePullPolicy: Always
        env:
        - name: PERSON_HOST
          value: udaconnect-person
        - name: PERSON_PORT
          value: "5000"
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
