apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-location
  name: udaconnect-location
spec:
  ports:
  - name: "location-svc-port"
    port: 5000
    targetPort: 5005
    nodePort: 30003
  selector:
    service: udaconnect-location
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-location
  name: udaconnect-location
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-location
  template:
    metadata:
      labels:
        service: udaconnect-location
    spec:
      containers:
      - image: vuongdq2503/udaconnect-location:latest
        name: udaconnect-location
        imagePullPolicy: Always
        env:
        - name: KAFKA_SERVER
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_SERVER
        - name: TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: TOPIC_NAME        
      restartPolicy: Always
